### ISSUE TITLE
Docker: 'docker-compose-monolith-mysql.yml up' not working

### ISSUE THREAD

**Issue by HalfUnitato** [eclipse-hawkbit/hawkbit#2128]
Hey guys,
I try to setup a simple hawkbit server using the provided docker-compose files.

`docker compose -f docker-compose-monolith-mysql.yml up`

but then hawkbit is throwing error about :
`Failed to load driver class org.mariadb.jdbc.Driver`

what in the docs am I missing? 

thanks in advance :)

```
docker-hawkbit-1   |  ______     _ _                  _                    _    ____  _ _

docker-hawkbit-1   |  |  ____|   | (_)                | |                  | |  |  _ \(_) |

docker-hawkbit-1   |  | |__   ___| |_ _ __  ___  ___  | |__   __ ___      _| | _| |_) |_| |_

docker-hawkbit-1   |  |  __| / __| | | '_ \/ __|/ _ \ | '_ \ / _` \ \ /\ / / |/ /  _ <| | __|

docker-hawkbit-1   |  | |___| (__| | | |_) \__ \  __/ | | | | (_| |\ V  V /|   <| |_) | | |_

docker-hawkbit-1   |  |______\___|_|_| .__/|___/\___| |_| |_|\__,_| \_/\_/ |_|\_\____/|_|\__|

docker-hawkbit-1   |                 | |

docker-hawkbit-1   |                 |_|

docker-hawkbit-1   |

docker-hawkbit-1   | Eclipse hawkBit Update Server  (v0.6.1)

docker-hawkbit-1   | using Spring Boot  (v3.3.5)

docker-hawkbit-1   |

docker-hawkbit-1   | Go to https://www.eclipse.org/hawkbit for more information.

docker-hawkbit-1   |

docker-hawkbit-1   |

docker-hawkbit-1   | 2024-12-06T19:19:46.042Z  INFO 1 --- [update-server] [:] [           main] org.eclipse.hawkbit.app.Start            : Starting Start v0.6.1 using Java 17.0.12 with PID 1 (/BOOT-INF/classes started by hawkbit in /)

docker-hawkbit-1   | 2024-12-06T19:19:46.046Z  INFO 1 --- [update-server] [:] [           main] org.eclipse.hawkbit.app.Start            : No active profile set, falling back to 1 default profile: "default"

docker-hawkbit-1   | 2024-12-06T19:19:47.553Z  INFO 1 --- [update-server] [:] [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.

docker-hawkbit-1   | 2024-12-06T19:19:47.793Z  INFO 1 --- [update-server] [:] [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 229 ms. Found 20 JPA repository interfaces.

docker-hawkbit-1   | 2024-12-06T19:19:48.488Z  INFO 1 --- [update-server] [:] [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'errorChannel' has been explicitly defined. Therefore, a default PublishSubscribeChannel will be created.

docker-hawkbit-1   | 2024-12-06T19:19:48.500Z  INFO 1 --- [update-server] [:] [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'integrationHeaderChannelRegistry' has been explicitly defined. Therefore, a default DefaultHeaderChannelRegistry will be created.

docker-hawkbit-1   | 2024-12-06T19:19:48.795Z  INFO 1 --- [update-server] [:] [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=d4a71ad1-30aa-322c-babe-755882b6092b

docker-hawkbit-1   | 2024-12-06T19:19:48.976Z  WARN 1 --- [update-server] [:] [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration$Hikari' of type [org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration$Hikari] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected/applied to a currently created BeanPostProcessor [methodValidationPostProcessor]? Check the corresponding BeanPostProcessor declaration and its dependencies/advisors. If this bean does not have to be post-processed, declare it with ROLE_INFRASTRUCTURE.

docker-hawkbit-1   | 2024-12-06T19:19:48.988Z  WARN 1 --- [update-server] [:] [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.commons.config.CommonsConfigAutoConfiguration' of type [org.springframework.cloud.commons.config.CommonsConfigAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected/applied to a currently created BeanPostProcessor [methodValidationPostProcessor]? Check the corresponding BeanPostProcessor declaration and its dependencies/advisors. If this bean does not have to be post-processed, declare it with ROLE_INFRASTRUCTURE.

docker-hawkbit-1   | 2024-12-06T19:19:48.991Z  WARN 1 --- [update-server] [:] [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.client.loadbalancer.LoadBalancerDefaultMappingsProviderAutoConfiguration' of type [org.springframework.cloud.client.loadbalancer.LoadBalancerDefaultMappingsProviderAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected/applied to a currently created BeanPostProcessor [methodValidationPostProcessor]? Check the corresponding BeanPostProcessor declaration and its dependencies/advisors. If this bean does not have to be post-processed, declare it with ROLE_INFRASTRUCTURE.

docker-hawkbit-1   | 2024-12-06T19:19:48.992Z  WARN 1 --- [update-server] [:] [           main] trationDelegate$BeanPostProcessorChecker : Bean 'loadBalancerClientsDefaultsMappingsProvider' of type [org.springframework.cloud.client.loadbalancer.LoadBalancerDefaultMappingsProviderAutoConfiguration$$Lambda$654/0x00007193ea4c0c80] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected/applied to a currently created BeanPostProcessor [methodValidationPostProcessor]? Check the corresponding BeanPostProcessor declaration and its dependencies/advisors. If this bean does not have to be post-processed, declare it with ROLE_INFRASTRUCTURE.

docker-hawkbit-1   | 2024-12-06T19:19:48.994Z  WARN 1 --- [update-server] [:] [           main] trationDelegate$BeanPostProcessorChecker : Bean 'defaultsBindHandlerAdvisor' of type [org.springframework.cloud.commons.config.DefaultsBindHandlerAdvisor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected/applied to a currently created BeanPostProcessor [methodValidationPostProcessor]? Check the corresponding BeanPostProcessor declaration and its dependencies/advisors. If this bean does not have to be post-processed, declare it with ROLE_INFRASTRUCTURE.

docker-hawkbit-1   | 2024-12-06T19:19:49.001Z  WARN 1 --- [update-server] [:] [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration' of type [org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected/applied to a currently created BeanPostProcessor [methodValidationPostProcessor]? Check the corresponding BeanPostProcessor declaration and its dependencies/advisors. If this bean does not have to be post-processed, declare it with ROLE_INFRASTRUCTURE.

docker-hawkbit-1   | 2024-12-06T19:19:49.003Z  WARN 1 --- [update-server] [:] [           main] trationDelegate$BeanPostProcessorChecker : Bean 'stringOrNumberMigrationVersionConverter' of type [org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$StringOrNumberToMigrationVersionConverter] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected/applied to a currently created BeanPostProcessor [methodValidationPostProcessor]? Check the corresponding BeanPostProcessor declaration and its dependencies/advisors. If this bean does not have to be post-processed, declare it with ROLE_INFRASTRUCTURE.

docker-hawkbit-1   | 2024-12-06T19:19:49.017Z  WARN 1 --- [update-server] [:] [           main] trationDelegate$BeanPostProcessorChecker : Bean 'spring.datasource-org.springframework.boot.autoconfigure.jdbc.DataSourceProperties' of type [org.springframework.boot.autoconfigure.jdbc.DataSourceProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected/applied to a currently created BeanPostProcessor [methodValidationPostProcessor]? Check the corresponding BeanPostProcessor declaration and its dependencies/advisors. If this bean does not have to be post-processed, declare it with ROLE_INFRASTRUCTURE.

docker-hawkbit-1   | 2024-12-06T19:19:49.020Z  WARN 1 --- [update-server] [:] [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration$PooledDataSourceConfiguration' of type [org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration$PooledDataSourceConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected/applied to a currently created BeanPostProcessor [methodValidationPostProcessor]? Check the corresponding BeanPostProcessor declaration and its dependencies/advisors. If this bean does not have to be post-processed, declare it with ROLE_INFRASTRUCTURE.

docker-hawkbit-1   | 2024-12-06T19:19:49.022Z  WARN 1 --- [update-server] [:] [           main] trationDelegate$BeanPostProcessorChecker : Bean 'jdbcConnectionDetails' of type [org.springframework.boot.autoconfigure.jdbc.PropertiesJdbcConnectionDetails] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected/applied to a currently created BeanPostProcessor [methodValidationPostProcessor]? Check the corresponding BeanPostProcessor declaration and its dependencies/advisors. If this bean does not have to be post-processed, declare it with ROLE_INFRASTRUCTURE.

docker-hawkbit-1   | 2024-12-06T19:19:49.026Z ERROR 1 --- [update-server] [:] [           main] com.zaxxer.hikari.HikariConfig           : Failed to load driver class org.mariadb.jdbc.Driver from HikariConfig class classloader org.springframework.boot.loader.launch.LaunchedClassLoader@2f92e0f4

docker-hawkbit-1   | 2024-12-06T19:19:49.030Z  WARN 1 --- [update-server] [:] [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'repositoryApplicationConfiguration' defined in URL [jar:file:/BOOT-INF/lib/hawkbit-repository-jpa-0.6.1.jar!/org/eclipse/hawkbit/repository/jpa/RepositoryApplicationConfiguration.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception with message: Failed to load driver class org.mariadb.jdbc.Driver in either of HikariConfig class loader or Thread context classloader

docker-hawkbit-1   | 2024-12-06T19:19:49.054Z  INFO 1 --- [update-server] [:] [           main] .s.b.a.l.ConditionEvaluationReportLogger :

docker-hawkbit-1   |

docker-hawkbit-1   | Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.

docker-hawkbit-1   |

docker-hawkbit-1   | 2024-12-06T19:19:49.077Z ERROR 1 --- [update-server] [:] [           main] o.s.boot.SpringApplication               : Application run failed

docker-hawkbit-1   |

docker-hawkbit-1   | org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'repositoryApplicationConfiguration' defined in URL [jar:file:/BOOT-INF/lib/hawkbit-repository-jpa-0.6.1.jar!/org/eclipse/hawkbit/repository/jpa/RepositoryApplicationConfiguration.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception with message: Failed to load driver class org.mariadb.jdbc.Driver in either of HikariConfig class loader or Thread context classloader

docker-hawkbit-1   |    at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:795) ~[spring-beans-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:237) ~[spring-beans-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1375) ~[spring-beans-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1212) ~[spring-beans-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562) ~[spring-beans-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337) ~[spring-beans-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335) ~[spring-beans-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:409) ~[spring-beans-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1355) ~[spring-beans-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1185) ~[spring-beans-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562) ~[spring-beans-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337) ~[spring-beans-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335) ~[spring-beans-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:205) ~[spring-beans-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:265) ~[spring-context-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:806) ~[spring-context-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:609) ~[spring-context-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.3.5.jar:3.3.5]

docker-hawkbit-1   |    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.3.5.jar:3.3.5]

docker-hawkbit-1   |    at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.3.5.jar:3.3.5]

docker-hawkbit-1   |    at org.springframework.boot.SpringApplication.run(SpringApplication.java:335) ~[spring-boot-3.3.5.jar:3.3.5]

docker-hawkbit-1   |    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363) ~[spring-boot-3.3.5.jar:3.3.5]

docker-hawkbit-1   |    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352) ~[spring-boot-3.3.5.jar:3.3.5]

docker-hawkbit-1   |    at org.eclipse.hawkbit.app.Start.main(Start.java:41) ~[classes/:0.6.1]

docker-hawkbit-1   |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]

docker-hawkbit-1   |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]

docker-hawkbit-1   |    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]

docker-hawkbit-1   |    at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]

docker-hawkbit-1   |    at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:102) ~[file:/:na]

docker-hawkbit-1   |    at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:64) ~[file:/:na]

docker-hawkbit-1   |    at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:40) ~[file:/:na]

docker-hawkbit-1   | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception with message: Failed to load driver class org.mariadb.jdbc.Driver in either of HikariConfig class loader or Thread context classloader

docker-hawkbit-1   |    at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:648) ~[spring-beans-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:636) ~[spring-beans-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1355) ~[spring-beans-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1185) ~[spring-beans-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562) ~[spring-beans-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337) ~[spring-beans-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335) ~[spring-beans-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[spring-beans-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1443) ~[spring-beans-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353) ~[spring-beans-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:904) ~[spring-beans-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:782) ~[spring-beans-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    ... 35 common frames omitted

docker-hawkbit-1   | Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception with message: Failed to load driver class org.mariadb.jdbc.Driver in either of HikariConfig class loader or Thread context classloader

docker-hawkbit-1   |    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:178) ~[spring-beans-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:644) ~[spring-beans-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    ... 49 common frames omitted

docker-hawkbit-1   | Caused by: java.lang.RuntimeException: Failed to load driver class org.mariadb.jdbc.Driver in either of HikariConfig class loader or Thread context classloader

docker-hawkbit-1   |    at com.zaxxer.hikari.HikariConfig.setDriverClassName(HikariConfig.java:494) ~[HikariCP-5.1.0.jar:na]

docker-hawkbit-1   |    at org.springframework.boot.jdbc.DataSourceBuilder$MappedDataSourceProperty.set(DataSourceBuilder.java:479) ~[spring-boot-3.3.5.jar:3.3.5]

docker-hawkbit-1   |    at org.springframework.boot.jdbc.DataSourceBuilder$MappedDataSourceProperties.set(DataSourceBuilder.java:373) ~[spring-boot-3.3.5.jar:3.3.5]

docker-hawkbit-1   |    at org.springframework.boot.jdbc.DataSourceBuilder.build(DataSourceBuilder.java:183) ~[spring-boot-3.3.5.jar:3.3.5]

docker-hawkbit-1   |    at org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration.createDataSource(DataSourceConfiguration.java:59) ~[spring-boot-autoconfigure-3.3.5.jar:3.3.5]

docker-hawkbit-1   |    at org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration$Hikari.dataSource(DataSourceConfiguration.java:117) ~[spring-boot-autoconfigure-3.3.5.jar:3.3.5]

docker-hawkbit-1   |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]

docker-hawkbit-1   |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]

docker-hawkbit-1   |    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]

docker-hawkbit-1   |    at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]

docker-hawkbit-1   |    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:146) ~[spring-beans-6.1.14.jar:6.1.14]

docker-hawkbit-1   |    ... 50 common frames omitted

docker-hawkbit-1   |

docker-hawkbit-1   |

docker-hawkbit-1 exited with code 0
                                                                
```

**Comment by avgustinmm** [comment]
Hi @HalfUnitato,
are you trying to run 0.6.1 with the docker compose yml from the _master_? If so, it won't work, because it assumes that mariadb java client is packed into the default monolith runtime - it is true for the master and should be true for the next release but it's not the case in 0.6.1. In 0.6.1 there is a dedicated docker image for MySQL packing the driver.
You could try using the docker yml from the 0.6.1 tag - [docker](https://github.com/eclipse-hawkbit/hawkbit/tree/0.6.1/hawkbit-runtime/docker).

**Comment by HalfUnitato** [comment]
Hi @avgustinmm,
yes, I used the master-branch.
Tag 0.6.1 is working, thank you very much :)

**Comment by shahzi176** [comment]
Hi Guys, I am sorry If I sound dumb, But I am also trying to setup Hawkbit from docker compose (docker-compose -f docker-compose-deps-mysql.yml -f docker-compose-monolith-mysql.yml up -d)
Intially I tired with docker compose monolith up but it thrown errro of include doesn't work so I commented Include and added both deps and monolith in same command, post that it throws error of maria db however I am trying to start it with MySQL: "Failed to load driver class org.mariadb.jdbc.Driver from HikariConfig class classloader org.springframework.boot.loader.launch.LaunchedClassLoader@2f92e0f4" can you guide me please. thanks
